### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by dakrone** [jdee-emacs/jdee#11]
I notice when I search online there are a handful of different maven integrations for JDEE. Does the jdee project have any official stance on these, or on using maven with the project at all?

I would love to use jdee but have an extremely complicated maven setup for my project and JDEE doesn't seem to correctly be able to compile anything.

EDIT: if Maven is not going to be supported, consider this a feature request to add that to the documentation somewhere.

**Comment by daveloyall** [comment]
This has been discussed recently.

See https://github.com/jdee-emacs/jdee/wiki/Roadmap and http://sourceforge.net/p/jdee/mailman/jdee-devel/?viewmonth=201507 (this last link is imprecise).

**Comment by dakrone** [comment]
Great, thanks for the response. Is there anything I can do to help with this? I'm happy to test on a very large and complex Java project (https://github.com/elastic/elasticsearch) that uses Maven, and I will happily donate money to help development along for this.

**Comment by pwojnowski** [comment]
Please provide links to those Maven integrations that you've found.

But I wouldn't expect in to be working soon. AFAIK malabar-mode (https://github.com/m0smith/malabar-mode) has support for Maven, so you can try it.

**Comment by phillord** [comment]
My solution would be turn this backward. Instead of having JDEE support maven, we make maven support JDEE. Assuming JDEE moves to an nrepl based background, we would just use maven to launch nrepl, then have JDEE probe the nrepl connection to get the data it needs (source code, completions etc).

**Comment by dakrone** [comment]
Here are the links to the ones I've found:

- [jde-maven.el](http://www.emacswiki.org/emacs/jde-maven.el)
- [pom-parser.el](http://www.emacswiki.org/emacs/JdeeAndMaven2Pom)
- [maven jdee plugin](http://maven.apache.org/archives/maven-1.x/plugins/jdee/) (the page says it is outdated)
- [pom.el](http://www.emacswiki.org/emacs/pom.el)
- [m2jdee](https://code.google.com/p/m2jdee/) another Maven plugin
- [jdee-mvn](https://github.com/crazia/jdee-mvn)
- [maven-emacs-plugin](https://github.com/credmp/maven-emacs-plugin)

**Comment by plandes** [comment]
Ideally be the operative word since nrepl is not currently in a state to where we can use it out of the box (please correct me if I'm wrong).

If it were me writing code (and who knows--could be) I'd just create a new leiningen clojure project that uses maven APIs to get maven project information that's given back to Emacs.  Keep it simple and refactor later to make a more general API for gradle when/if there's someone who wants it.

**Comment by dakrone** [comment]
> Ideally be the operative word since nrepl is not currently in a state to where we can use it out of the box (please correct me if I'm wrong).

I guess it depends on what you mean by "out of the box", what do you need nrepl to do? Return source code, completion, etc?

**Comment by plandes** [comment]
Basically--interface to the JVM in general.  I don't know the details but there was an earlier thread regarding some more work that needed to be done to get it up to speed, which would obviate cider as a dependency.

On a related note: I'm fine with making cider a dependency.

**Comment by phillord** [comment]
So -- terminology. "nrepl-server" -- there is a maven plugin providing this and it should be usable. "nrepl-middleware" -- the code that does what ever we need it too domain wise (i,e. completions etc), I don't know. Some of it will need writing, some of it can be borrowed, some of it can be ported from bsh. "nrepl-client" exists and should be usuable, but is currently bundled with cider. So usuable, but with baggage.

**Comment by plandes** [comment]
Cogent explanation--thanks Phillip.

**Comment by phillord** [comment]
Paul Landes <notifications@github.com> writes:

> Cogent explanation--thanks Phillip.


I guess that the way forward from here is me to knock up a proof of
principle exemplar...

**Comment by jahlborn** [comment]
i'm not sure what all functionality you are looking for, but i find pom-parser to fit my needs.

**Comment by tokomakoma123** [comment]
I've borrowed from jdee-maven2.el and modified as follows: 
https://gist.github.com/tokomakoma123/721c9901c896f2f462f43754b3472d1b

It works fine with jdee.

I made some modifications for the original m2jdee.
original - https://github.com/songuo/m2jdee
mine - ://github.com/tokomakoma123/m2jdee

**Comment by m0smith** [comment]
There is a pull request for a basic maven integeration: https://github.com/jdee-emacs/jdee/pull/72

**Comment by plandes** [comment]
Thanks Matt.

Questions:

Are all the changes you're making new functionality?

Are you replacing beanshell with groovysh?

Are the changes you're making adding groovysh to JDEE and are those changes decoupled from the rest of the project?

How many of the changes are modifying what's already there?

Thanks.

**Comment by m0smith** [comment]
I am only adding new functionality for now or fixing bugs.  I do not see a reason to remove existing functionality.  I may modify existing functionality to accommodate the changes but will strive to make the changes invisible to a user.

I am not replacing bsh at this point.  The things I want to make happen first can work in bsh.  When I get around to it, I will be making groovysh an option to use instead of bsh.  The idea being that a user can use whichever Java shell they want.  As I implement groovysh it will be with an eye toward making it easier to implement other shells (cider, JShell, etc) in the future.

My changes have been made with minimal modifications to existing code.  The maven integration provides an additional mechanism for setting the project variables rather than replacing or removing existing functionality.  I will continue

**Comment by plandes** [comment]
Hi Przemysław,

Did you merge in all of his changes?  If so, we now have groovysh doing various maven tasks?

**Comment by pwojnowski** [comment]
Yes, I merged whole PR and no, there is no groovysh.
This PR had only Maven support and was calling Maven directly - see jdee-maven.el for details.

**Comment by plandes** [comment]
Thank you.  Is it tested?

**Comment by plandes** [comment]
Matt: That sounds like a good plan.  Thanks for your contributions and an attention to our concerns.
