### ISSUE TITLE
Idle Parse Error

### ISSUE THREAD

**Issue by kostafey** [jdee-emacs/jdee#137]
### My Emacs version:
GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2017-06-04
### My JDEE version (elpa package date):
20171007.835
### My JDK version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### My Operating System (Linux/OSX/Windows X/Other): 
Linux debian-pc 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linu
### Stacktrace (if applicable): 
Idle Parse Error: "#<buffer SpringDemoApplication.java> - Invalid slot type: jdee-parse-method-map, tree, sequence, #s(avl-tree- [nil nil nil 0] jdee-parse-method-map-compare-fcn)"
### How to reproduce (if applicable): 
`save-buffer`

**Comment by kostafey** [comment]
Reinstalling all files from ELPA as described in #124 can't' help in my case.

**Comment by pwojnowski** [comment]
If the solution from #124 doesn't help, then I'm not sure what else could be.
AFAIK these kind of problems are caused by version mismatch between libraries - usually JDEE compiled with an older EIEIO for older Emacs is run in a newer Emacs. So I would double check that and try to run it in an emacs without additional packages or something like this.

**Comment by kostafey** [comment]
```
rm -R ~/.emacs.d/elpa/
emacs -Q
```
eval:
```lisp
(setq package-archives '(("ELPA" . "http://tromey.com/elpa/")
                         ("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")
                         ("m-stable" . "http://stable.melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")))
```
`M-x package-install [RET] jdee [RET]`
Then open some java file. Result:
```
eieio--validate-slot-value: Invalid slot type: jdee-parse-method-map, tree, sequence, #s(avl-tree- [nil nil nil 0] jdee-parse-method-map-compare-fcn)
```

**Comment by johnae** [comment]
I have the same problem. Reinstalling everything didn't seem to help.

Emacs version:
```
GNU Emacs 27.0.50
```

OS:
```
Arch Linux
```

Java version:
```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by pwojnowski** [comment]
Thank you @jahlborn for investigating the issue! :medal_military: 
I've changed the type to "avl-tree-", because it's also available in Emacs 25, so it can be used in both versions. Please, verify if it actually fixes the issue in Emacs 26 - I still have to setup Docker with different Emacs versions. :cry:
