### ISSUE TITLE
Incomplete package at MELPA?

### ISSUE THREAD

**Issue by nyambol** [jdee-emacs/jdee#23]
Is the jdee package at MELPA expected to be complete? It does not include jdee-server, nor the jars such as bsh.jar.  The package currently available for install is `jdee-20150920.635`.  I don't know if there is supposed to be a secondary call during the package building stage, but I'm ending up with no jars.  

`Ubuntu 15.04`
`GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.9)  of 2015-03-21 on kissel, modified by Debian`

**Comment by pwojnowski** [comment]
It is complete elisp package. The JVM counterpart have to be installed separately, which is not a big problem, because it doesn't change very often.
This will be fixed sometime, but it's not of highest priority.
I'll correct the message about jdee-server installation to make it clear that it has to be done manually.
