### ISSUE TITLE
Not all font-lock variables work

### ISSUE THREAD

**Issue by theldoria** [jdee-emacs/jdee#37]
I can change the used font lock for some fontification, e.g. these work:

    (setq jdee-font-lock-constant-face 'font-lock-constant-face)
    (setq jdee-font-lock-modifier-face 'font-lock-keyword-face)

but (at least) these three do not work:

    (setq jdee-font-lock-public-face 'font-lock-keyword-face)
    (setq jdee-font-lock-private-face 'font-lock-keyword-face)
    (setq jdee-font-lock-protected-face 'font-lock-keyword-face)

**Comment by oldButNotWise** [comment]
There is some confusion in Emacs about how face names should be handled. The Info page for defining faces says:

>People are sometimes tempted to create a variable whose value is a
>face name.  In the vast majority of cases, this is not necessary; the
>usual procedure is to define a face with ‘defface’, and then use its
>name directly.

On the other hand the file font-lock.el says

>So the easiest thing is to continue using these variables,
>rather than sometimes evalling FACENAME and sometimes not.

jdee-font-lock.el defines both the faces and the variables (following the style from font-lock.el). But some (not all) of the font lock expressions defined in the file explicitly quote the face name
```
	`(,(c-make-font-lock-search-function
	    "\\<\\(public\\)\\>"
	    '(1 'jdee-font-lock-public-face t)))
```
The fix is to drop these quotes on the face names. A work-around would be to directly modify the jdee-font-lock-XXX-face.

**Comment by theldoria** [comment]
I wanted to use existin face as jdee face. So I came up with a workaround using ```copy-face```:

```lisp
(copy-face 'font-lock-doc-face 'jdee-font-lock-javadoc-face)
```

**Comment by oldButNotWise** [comment]
The fix is now in the master brach.

**Comment by pwojnowski** [comment]
If it is still an issue then please reopen it.
