### ISSUE TITLE
Parenthesis matching error

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#80]
Latest jdee (20161102.531) from elpa, does not match correctly parenthesis on this line:

```
final static private Pattern pattFlName = Pattern.compile("([-'A-Za-z .]+)[ ,;]+([-'A-Za-z]+)$");
final static private Pattern pattLfName = Pattern.compile("^([-'A-Za-z]+)[ ,;]+([-'A-Za-z .]+)");
```
When moving cursor to the first closing paren, it is highlighted as if it did not match anything. When moving the cursor to the second opening paren, it matches the first closing paren of the **second line**!!

**Comment by m0smith** [comment]
Which paren matching package are you using?

**Comment by liar666** [comment]
Not sure how to determine that.

I'm using default config under "GNU Emacs 24.5.1"

**Comment by m0smith** [comment]
Assuming you are using `show-paren-mode` it looks like the single quote `'` is confusing the parser as it sees it as something that needs a match.  If you change the syntax to make `'` a `w` rather than a `"` for regexp that should do  it.

I have no idea how to do this just within a String that looks like a regexp.

As far as I can test, this is not a JDEE issue.

**Comment by pwojnowski** [comment]
To me it also doesn't look like problem with JDEE. So we cannot help here.
